POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoiNjFhMzg5M2ZhODkyYWIyNWVmMWFkODM3IiwiaWF0IjoxNjM4MTA4MTQ2fQ.f7LN_QXiaUNWOWik7Ot-kuvr7AGIzVWP3RyUwIM1jkE

{
  "title": "newtitle6",
  "author": "newauthorla6",
  "url": "blabla6",
  "likes": 8
}